apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: addon-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: ArgoCD project for deploying addons
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  sourceRepos:
    - '*'
  orphanedResources: 
    warn: true